# Generated by Django 4.0.5 on 2022-06-05 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codewriter', '0003_remove_test_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
